### ISSUE TITLE
failure when trying to replace "MessageBoxA" with an user defined function

### ISSUE THREAD

**Issue by YoavLevi** [maziland/StackBombing#1]
Hey everybody,
I tried the following:
replacing line 257 in Rop_Chain.cpp --> FunctionCall((DWORD64)MessageBoxA, 0, 0, 0, 0);
with the following line --> FunctionCall((DWORD64)MessageBoxB, 0, 0, 0, 0);
where MessageBoxB is an user defined function with the same signature as MessageBoxA:

int WINAPI MessageBoxB(
	_In_opt_ HWND hWnd,
	_In_opt_ LPCSTR lpText,
	_In_opt_ LPCSTR lpCaption,
	_In_ UINT uType)
{
	return MessageBoxA(NULL, "IM INJECTED", "MessageBoxB", MB_OK);
}

It was compiled successfully but when executed it caused the target process to crash.
what am I doing wrong?
Alternatively, how can I make this happen so I can inject user defined functions successfully?

Thanks in advance,

**Comment by maziland** [comment]
Hey Yoav,
I'm glad you came up with such question :)
Have you read my digitalwhisper article?

Anyway, the reason you are getting such an error is because StackBombing
only relies on functions in shared memory addresses.

The function MessageBoxB doesn't exist in user32.dll, but only inside your
StackBombing.exe image. However, MessageBoxA is a function that exists in
both processes memory: the injector and the injected.

The ROP chain can only be built with existing functions in shared memory.

Hope I managed to answer your question,
Feel free to contact me if you have any further questions :-)

**Comment by YoavLevi** [comment]
Thanks so much Alon, now it makes more sense, I probably missed that part of your interesting article.
One last question :)
Can you mention a way for passing arguments for the called function in shared memory addresses? (e.g MessageBoxA)
I didn't found a clue for that in the code.

**Comment by maziland** [comment]
Of course, well that's a functionality I haven't implemented yet because of
complexity and lack of time.

I'm willing to write it and document as well. If you look at the code in
the bottom of ROP_Chain.cpp you'll see "insert text to stack".
That's the way of doing so if that interests you.

Anyway, soon I'll make sure it will be a part of the FunctionCall()
function.

Thanks!

**Comment by YoavLevi** [comment]
OK I'll keep following,
Thanks again!
